### ISSUE TITLE
Uncaught ReferenceError: tizentvwasm is not defined

### ISSUE THREAD

**Issue by parthagraz** [SamsungDForum/WebAssemblyDemos#1]
Hi Samsung forum,
I have followed the steps which were mentioned in the readme.md file.
But when i was running this on tv emulator 5.5, giving the below error.

![image](https://user-images.githubusercontent.com/72971230/98227639-8bb1f200-1f7d-11eb-815b-c4ca68075781.png)

And when i run this on Samsung tv,
It says Cannot load WASM module.

![image](https://user-images.githubusercontent.com/72971230/98232108-41337400-1f83-11eb-8c22-26b41dca17e1.png)

Can you please mention the what is the problem.

**Comment by MartaPawlowska** [comment]
What is the TV image you are tesing it on?

**Comment by parthagraz** [comment]
> What is the TV image you are tesing it on?

Model Code : QB43N

**Comment by MartaPawlowska** [comment]
Please follow instruction to check image version: https://www.samsung.com/uk/support/tv-audio-video/how-can-i-check-what-software-version-my-tv-is-using

**Comment by parthagraz** [comment]
> Please see: https://www.samsung.com/uk/support/tv-audio-video/how-can-i-check-what-software-version-my-tv-is-using

Software Version : T-KTM2ELAKUC-1110.1

**Comment by parthagraz** [comment]
Can I test this demo on tv emulator?

**Comment by MartaPawlowska** [comment]
WASM is supported on TV from 2020 models.

As of emulator WASM is working however no TV related WASM features are not included - sockets and wasm_player. For testing TV related features on emulator you need partner SDK version.

**Comment by parthagraz** [comment]
> WASM is supported on TV from 2020 models.
> 
> As of emulator WASM is working however no TV modules are not included - sockets and wasm_player. For testing TV related features on emulator you need partner SDK version.

Ok

I have downloaded the emsdk and stored them to the manual path. 
And emscripten config and cache are stored on there default location.

So can you tell me the approach to include TV module in tizen studio from custom path. because I have provided the path of emscripten toolchain. still why it cannot include TV modules.

What is partner SDK version. because i have downloaded all the sdk version which are required for wasm.

**Comment by MartaPawlowska** [comment]
I've corrected TV Modules to TV related WASM features. On currently available version you can not test our examples. In few months there will be new version available, therefore you need to wait for that. 

Our demos contains code that is using TV related changes (curl - sockets, wasm player) therefore to test it currently only possible way is to build it and test it on TV 2020.

**Comment by parthagraz** [comment]
And can you also provide me the alternative approach to create tv widget with the help of c/c++. for products before 2020.

Note :- Except NaCl, because this is also deprecated.

**Comment by MartaPawlowska** [comment]
NaCl is deprecated, but it is still supported on Samsung TVs. Please contact NaCl team for further information.

**Comment by parthagraz** [comment]
Thank you @MartaPawlowska for the support.
It was very much helpful.

**Comment by parthagraz** [comment]
> NaCl is deprecated, but it is still supported on Samsung TVs. Please contact NaCl team for further information.

How can I connect to NaCl team.

**Comment by MartaPawlowska** [comment]
You have guide for NaCl here: https://developer.samsung.com/smarttv/develop/extension-libraries/nacl/overview.html

**Comment by parthagraz** [comment]
Ok Thank you so much.
